name: Bug report
description: Report a defect or unexpected behaviour
labels: ["type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What went wrong?
    validations:
      required: true
