name: Feature request
description: Suggest a new feature or improvement
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Reminder:** Please set **Issue type = Feature** before submitting.

  - type: textarea
    id: summary
    attributes:
      label: What is the feature?
      description: Describe the problem or improvement.
    validations:
      required: true
