name: Feature request
description: Suggest a new feature or improvement
labels: ["type:feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: What is the feature?
    validations:
      required: true
